// Desktop/ProjectTCM/massage-studio-webapp/frontend/src/components/Home/Home.tsx
// Home.tsx
import './Home.css';

// Home.tsx
export const Home = () => {
    const services = [
      { title: 'Traditional Massage', description: 'Ancient healing techniques', image: '/images/TCM1.jpg' },
      { title: 'Acupuncture', description: 'Targeted pain relief', image: '/images/TCM2.jpg' },
      { title: 'Cupping', description: 'Deep tissue therapy', image: '/images/TCM3.jpg' },
      { title: 'Chinese Medicine', description: 'Holistic healing', image: '/images/TCM5.jpg' }
    ];

 return (
   <div className="container">
     <div className="grid">
       {services.map(service => (
         <div key={service.title} className="card">
           <img src={service.image} alt={service.title} />
           <div className="content">
             <h2>{service.title}</h2>
             <p>{service.description}</p>
             <button>Details</button>
           </div>
         </div>
       ))}
     </div>
   </div>
 );
};

// Desktop/ProjectTCM/massage-studio-webapp/frontend/src/app/components/home/home.component.ts
// home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
 selector: 'app-home',
 standalone: true,
 imports: [CommonModule],
 templateUrl: './home.component.html',
 styleUrls: ['./home.component.css']
})
export class HomeComponent {
 services = [
   { title: 'Traditional Massage', description: 'Ancient healing techniques', image: 'https://via.placeholder.com/400x300' },
   { title: 'Acupuncture', description: 'Targeted pain relief', image: 'https://via.placeholder.com/400x300' },
   { title: 'Cupping', description: 'Deep tissue therapy', image: 'https://via.placeholder.com/400x300' }
 ];
}
<!-- home.component.html -->
<div class="container">
    <div class="grid">
      @for (service of services; track service.title) {
        <div class="card">
          <img [src]="service.image" [alt]="service.title"/>
          <div class="content">
            <h2>{{service.title}}</h2>
            <p>{{service.description}}</p>
            <button>Details</button>
          </div>
        </div>
      }
    </div>
  </div>
